name: POC-19 

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Testing
        run: echo "CI: Checking code one last time... Pass!"

  deploy-to-production:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploying
        run: |
          echo "CD: Launching Rocket Ship..."
          echo "Your project is now LIVE on the server!"
