name: POC-19
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Testing
        run: echo "CI Pass"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploying
        run: echo "CD Pass"
